### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [abdallahmehiz/mpvKt#9]
First thanks for making your app available freely under a FOSS license! I just took the freedom to have it added to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid), where it will show up with the next sync in about an hour from now. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to [link there](https://apt.izzysoft.de/packages/live.mehiz.mpvkt) e.g. from your Readme here!

A few questions I'd have concerning the requested permissions. `android.permission.READ_MEDIA_AUDIO` and `android.permission.READ_MEDIA_VIDEO` are clear of course (and thus already have been added to the app's "green list" with the corresponding explanations). But is the app also intended as photo gallery, that `android.permission.READ_MEDIA_IMAGES` is requested? And what for is the "old" `android.permission.READ_EXTERNAL_STORAGE` (minimum Android version required is 5, so I assume you're using Storage Access Framework) – and what does the app write so it needs `android.permission.WRITE_EXTERNAL_STORAGE`?

-----

At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I was able to successfully generate the APK using `./gradlew assembleRelease`, but the resulting APKs were not identical. That is a.o. because you insert timestamps at build-time, in at least 2 places. One is [here](https://github.com/abdallahmehiz/mpvKt/blob/main/app/build.gradle.kts#L33) (I'd suggest to leave the timestamp out there, the commit hash should be totally sufficient) – the other is with AboutLibraries:

APK Diff:

```diff
  -rw-r--r--  0.0 unx      120 b-      118 defN 1981-01-01 01:01:02 bec2f133 META-INF/version-control-info.textproto
- -rw-r--r--  0.0 unx     5313 b-     5313 stor 1981-01-01 01:01:02 a7865aaf assets/dexopt/baseline.prof
+ -rw-r--r--  0.0 unx     5314 b-     5314 stor 1981-01-01 01:01:02 be4c8181 assets/dexopt/baseline.prof
  -rw-r--r--  0.0 unx      465 b-      465 stor 1981-01-01 01:01:02 f3df7488 assets/dexopt/baseline.profm
- -rw-r--r--  0.0 unx  4740532 b-  2161059 defN 1981-01-01 01:01:02 3fc0a844 classes.dex
+ -rw-r--r--  0.0 unx  4740532 b-  2161058 defN 1981-01-01 01:01:02 a19d34e4 classes.dex
  -rw-r--r--  0.0 unx 13734288 b-  6759678 defN 1981-01-01 01:01:02 276a26f0 lib/arm64-v8a/libavcodec.so
  -rw-r--r--  0.0 unx     9072 b-     3439 defN 1981-01-01 01:01:02 93aa0a50 lib/arm64-v8a/libavdevice.so
  -rw-r--r--  0.0 unx  4183560 b-  1745872 defN 1981-01-01 01:01:02 d8bdf273 lib/arm64-v8a/libavfilter.so
@@ -340,7 +340,7 @@
  -rw----     0.0 fat      592 b-      317 defN 1981-01-01 01:01:02 d011bd16 res/Lt.xml
  -rw----     0.0 fat      132 b-       75 defN 1981-01-01 01:01:02 214428f8 res/Lv.xml
  -rw----     0.0 fat      612 b-      302 defN 1981-01-01 01:01:02 4145c11e res/M2.xml
- -rw----     0.0 fat    86773 b-    11916 defN 1981-01-01 01:01:02 bc2b7e8f res/M7.json
+ -rw----     0.0 fat    86773 b-    11916 defN 1981-01-01 01:01:02 e0e8d869 res/M7.json
  -rw----     0.0 fat     1196 b-      397 defN 1981-01-01 01:01:02 f0bf9426 res/M7.xml
```

This shows the `classes.dex` as the culprit (`baseline.prof` differences result of that as that file contains the checksum of the dex files). So let's look at that:

```diff
 |: new-instance v7, Ljava/lang/StringBuilder;
-|: const-string v10, "\n    App version: 0.1.0 (97b945b/2024-08-29T06:18:45)\n    Android version: "
+|: const-string v10, "\n    App version: 0.1.0 (97b945b/2024-08-31T17:03:05)\n    Android version: "
 |: invoke-direct {v7, v10}, Ljava/lang/StringBuilder;.<init>:(Ljava/lang/String;)V
 |: invoke-virtual {v7, v0}, Ljava/lang/StringBuilder;.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
 |: const-string v0, " ("
@@ -905152,7 +905152,7 @@
 |: const-string v0, "0.1.0"
 |: const/4 v5, #int 1 // #1
 |: aput-object v0, v6, v5
-|: const-string v0, "2024-08-29T06:18:45"
+|: const-string v0, "2024-08-31T17:03:05"
 |: aput-object v0, v6, v2
```

There are your timestamps. Last, `M7.json` is what AboutLibraries creates – and which can be cured easily by adding the following to your `build.gradle.kts`:

```kotlin
aboutLibraries {
    excludeFields = arrayOf("generated")
}
```

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

cc @obfusk

**Comment by abdallahmehiz** [comment]
> A few questions I'd have concerning the requested permissions. `android.permission.READ_MEDIA_AUDIO` and `android.permission.READ_MEDIA_VIDEO` are clear of course (and thus already have been added to the app's "green list" with the corresponding explanations). But is the app also intended as photo gallery, that `android.permission.READ_MEDIA_IMAGES` is requested? And what for is the "old" `android.permission.READ_EXTERNAL_STORAGE` (minimum Android version required is 5, so I assume you're using Storage Access Framework) – and what does the app write so it needs `android.permission.WRITE_EXTERNAL_STORAGE`?

tbf, mpvKt currently does not make use of any of these permissions. They're kind of left overs from the mpv-android lib I am using.
I've been planning on removing them by making my own fork of the library but haven't done so cause it didn't seem that important.
There is also some optimizations i'd like to make to the mpv-android lib i am currently using like removing some unused classes and such, I'll be looking into making these changes soon.

> At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I was able to successfully generate the APK using `./gradlew assembleRelease`, but the resulting APKs were not identical. That is a.o. because you insert timestamps at build-time, in at least 2 places. One is [here](https://github.com/abdallahmehiz/mpvKt/blob/main/app/build.gradle.kts?rgh-link-date=2024-08-31T17%3A29%3A39Z#L33) (I'd suggest to leave the timestamp out there, the commit hash should be totally sufficient) – the other is with AboutLibraries: ...

I've already found these and found solutions for it recently, as you can see from the screenshot, I got reproducible builds work successfully and i will be committing my changes soon
```
2024-08-31 18:43:20,444 INFO: ...successfully verified
2024-08-31 18:43:20,444 INFO: compared built binary to supplied reference binary successfully
2024-08-31 18:43:20,588 DEBUG: Using APK Signature v2
2024-08-31 18:43:20,599 WARNING: AllowedAPKSigningKeys missing but reference binary supplied
2024-08-31 18:43:20,602 DEBUG: skip deploying full build logs: not enabled in config
2024-08-31 18:43:20,602 INFO: success: live.mehiz.mpvkt
2024-08-31 18:43:20,602 INFO: Finished
2024-08-31 18:43:20,602 INFO: 1 build succeeded
2024-08-31 18:43:20,602 DEBUG: skip deploying full build logs: not enabled in config
2024-08-31 18:43:20,603 DEBUG: skip deploying full build logs: not enabled in config
```

And last, thank YOU for taking your valuable time to put this project of mine on your repositories. this means a lot to me.

**Comment by IzzySoft** [comment]
> I've been planning on removing them by making my own fork of the library but haven't done so cause it didn't seem that important.

Ah, thanks! So you'll do so with the next release then? In that case we can ignore them for now.

> I've already found these and found solutions for it recently, as you can see from the screenshot, I got reproducible builds work successfully and i will be committing my changes soon

Wonderful, much appreciated! As soon as a release with APK is available, please give me a ping and I start verification again. If you want to have it checked in advance of the release, all I'd need would be the APK and the commit it was built from.

**Comment by abdallahmehiz** [comment]
@IzzySoft I have released a version that supports reproducible builds!
and committed the necessary changes to [Gitlab merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15657)

**Comment by IzzySoft** [comment]
Thanks, taking a look now. But it seems like you're confusing something here: F-Droid.org has nothing to do with my issue here, we're talking about the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) here :wink:

Eh, and no, that won't work. Hardcodded URL (with the version inside) to fetch the timestamp from during build? You'll have a lot of fun with that, like each new release will be broken and take more than a week to show up at F-Droid after manual adjustments.

What for are those timestamps needed at all? Can't you simply remove them? What makes them so important to risk breaking things? And just for that the need to install multiple extra packages (jq, curl). And it will kill a few cute kittens. Couldn't you do entirely without them?

Got it to work now, though:

```yaml
---
repository: https://github.com/abdallahmehiz/mpvKt.git
updates: releases
versions:
  - tag: v0.1.1
    apks:
      - apk_pattern: mpvKt-arm64-v8a.*\.apk
        apk_url: https://github.com/abdallahmehiz/mpvKt/releases/download/v0.1.1/mpvKt-arm64-v8a-v0.1.1.apk
        build:
          - sed -r '/abi \{/,/}/ { s/include\(.*\)/include("arm64-v8a")/ ; s/isUniversalApk = true/isUniversalApk = false/ }' -i app/build.gradle.kts
          - timestamp="$(curl -sL https://github.com/abdallahmehiz/mpvKt/releases/download/${APP_TAG}/build-metadata.json | jq -r '.timestamp' | tr -cd 0-9)"
          - echo -e "\ntimestamp=$timestamp" >> gradle.properties
          - chmod +x gradlew
          - ./gradlew assembleRelease
          - mv app/build/outputs/apk/release/*unsigned.apk /outputs/unsigned.apk
        build_home_dir: /build
        build_repo_dir: /build/repo
        build_user: build
        provisioning:
          android_home: /opt/sdk
          build_tools:
          cmake:
          cmdline_tools:
            version: '12.0'
            url: https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            sha256: 2d2d50857e4eb553af5a6dc3ad507a17adf43d115264b1afc116f95c92e5e258
          extra_packages:
            - jq
            - curl
          image: debian:bookworm-slim
          jdk: openjdk-17-jdk-headless
          ndk:
          platform:
          platform_tools:
          tools:
          verify_gradle_wrapper: true
```

That's the recipe for the verification builder here. At IzzyOnDroid, the two are separate: we ship the APKs provided by the developers, and have them verified independently. Currently there are 2 builders running publicly, we hope for more in the future – especially for some run by people not on our team, to have them really independent. Details, as linked from the initial post: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) :wink: 

And [here's your welcome toot](https://floss.social/@IzzyOnDroid/113059070782110155):

![image](https://github.com/user-attachments/assets/69e9ed6b-a6bb-4041-a1bd-a163a024a2a1)

If you now want to read the first two lines of the initial post, maybe you will [pick and add the badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it)? :star_struck:
